name = "PosteriorPlots"
uuid = "196f2941-2d58-45ba-9f13-43a2532b2fa8"
authors = ["Trent Henderson <then6675@uni.sydney.edu.au>"]
version = "0.2.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
DataFrames = "0.22.7"
KernelDensity = "0.6.2"
MCMCChains = "4.10.0"
Plots = "1.13"
StatsBase = "0.33.8"
StatsPlots = "0.14"
julia = "1"
