name = "PosteriorPlots"
uuid = "196f2941-2d58-45ba-9f13-43a2532b2fa8"
authors = ["Trent Henderson <then6675@uni.sydney.edu.au> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
Plots = "1.13"
StatsPlots = "0.14"
KernelDensity = ""
julia = "1"

[targets]
test = ["Test"]
