name = "PosteriorPlots"
uuid = "196f2941-2d58-45ba-9f13-43a2532b2fa8"
authors = ["Trent Henderson <then6675@uni.sydney.edu.au> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "1.0"
Plots = "1.13"
StatsPlots = "0.14"
KernelDensity = "0.6.2"
Turing = "0.16.0"
StatsBase = "0.33.8"
julia = "1"

[targets]
test = ["Test"]
